### ISSUE TITLE
BUG : Capitalize newsletter in navbar in Mobile View

### ISSUE THREAD

**Issue by Sakhi29** [ratishjain12/aiclubwebsite#1]
I found this typo issue in Mobile View in Navbar for the last field that is newsletter which is not capitalized as others.

I have uploaded a screenshot for better understanding of the issue.
![image](https://github.com/ratishjain12/aiclubwebsite/assets/106910881/3b9929ce-8584-4035-9874-f255bebbfc32)

Please assign it to me @ratishjain12 Thankyou :)

**Comment by ratishjain12** [comment]
Go for it @Sakhi29
