### ISSUE TITLE
Logo Change to Croped image to Original Png

### ISSUE THREAD

**Issue by Vinay94278** [ratishjain12/aiclubwebsite#10]
![Problem](https://github.com/ratishjain12/aiclubwebsite/assets/106542979/d929d977-c3c9-46e5-a539-cf0f78bc41a1)

Here We are using a croped image of logo so we need to just changed it with official png
It is required because croped image is not aligning with navbars other options

**Comment by Vinay94278** [comment]
Hello @ratishjain12 I Have just solved this issue #11 just review it and merge it
Before

![Problem](https://github.com/ratishjain12/aiclubwebsite/assets/106542979/aa69a7fe-5d1d-4520-80e7-35c3fc2e117a)


After

![Solved](https://github.com/ratishjain12/aiclubwebsite/assets/106542979/b269d6e5-1b16-4cd2-98c9-0dfdb783191f)

**Comment by ratishjain12** [comment]
> Hello @ratishjain12 I Have just solved this issue #11 just review it and merge it
> Before
> 
> ![Problem](https://github.com/ratishjain12/aiclubwebsite/assets/106542979/aa69a7fe-5d1d-4520-80e7-35c3fc2e117a)
> 
> 
> After
> 
> ![Solved](https://github.com/ratishjain12/aiclubwebsite/assets/106542979/b269d6e5-1b16-4cd2-98c9-0dfdb783191f)
> 

Nice @Vinay94278 dont forget to star the repo 🌟
