### ISSUE TITLE
Enhancement : Add a scroll to top button  

### ISSUE THREAD

**Issue by kaushal1717** [ratishjain12/aiclubwebsite#4]
I want to add a scroll to the top button so it will be good for the website

**Comment by ratishjain12** [comment]
Go for it @kaushal1717 :)

**Comment by nainesh30** [comment]
> I want to add a scroll to the top button so it will be good for the website

Or else we can make the nav bar sticky so it stays always on top.

**Comment by ratishjain12** [comment]
@nainesh30  its fine as it is now
